[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "medspacy"
readme = "README.MD"
authors = [{name = "medSpaCy"}]
description = "Library for clinical NLP with spaCy."
requires-python = ">=3.8"
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
dynamic = ["version"]

# Hatch dependencies
[tool.hatch.metadata]
dependencies = [
    "Cython>=0.25,<3.0",
    "spacy>=3.0.0,<=3.6",
    "PyFastNER>=1.0.8",
    "quicksectx>=0.3.5"
]
# If you need to dynamically include dependencies from a requirements.txt file, 
# this will require a custom script or manual update.

[tool.hatch.version]
path = "medspacy/VERSION"

[project.urls]
Source = "https://github.com/medspacy/medspacy"

# Include additional package data
[tool.hatch.envs.default]
# Specify additional build settings here if necessary
