# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Packaging

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
        
    - name: Build package
      run: |
        hatch build
        # hatch publish

    - name: Check built
      run: ls dist
      
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: tar gz file
        path: dist
        retention-days: 2