name: medspacy

on:
  push:
    branches: [ master, develop, ci_debug ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
  
    # TODO: Do we care if this only runs on allowed branches since we check push/pull_request above?
    #if: github.ref == 'refs/heads/master' OR github.ref == 'refs/heads/develop'

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # removed 3.5 since there appears to be a failure with setuptools
        #python-version: [3.6, 3.7, 3.8] # [3.5, 3.6, 3.7, 3.8]
        #os: [ubuntu-latest, macos-latest, windows-2019]
        include:
          - name: "Ubuntu Python 3.8"
            os: ubuntu-latest
            python-version: 3.8
            addons:
              apt:
                update: true
                packages:
                  # These are the required system level updates for Ubuntu and spacy:
                  # https://spacy.io/usage#source-ubuntu
                  - build-essential
                  - python-dev
          - name: "MacOS Python 3.8"
            os: macos-latest
            python-version: 3.8
          - name: "Windows Python 3.8"
            os: windows-2019
            python-version: 3.8

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}   
        cache: 'pip'   
               
    - name: Install dependencies      
      run: |
        python --version
        python -m pip install --upgrade pip        
        # Install our package to make sure our setup works...
        pip install -e .
        # set up all spacy language models that are used in our pytest tests
        python -m spacy download en_core_web_sm
        pip install flake8 pytest

    - name: print medspacy version
      run: python -c 'import medspacy; print(medspacy.__version__); print(medspacy.__file__)'
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        # run everything besides the QuickUMLS span group tests...
        pytest -k "not test_span_groups and not test_overlapping_spans and not test_multiword_span"
        # now in a separate session we can run the QuickUMLS span group tests...
        pytest -k "test_span_groups or test_overlapping_spans or test_multiword_span"
